name: unit4wk2
channels:
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py37_0
  - cycler=0.10.0=py37_0
  - decorator=4.4.0=py37_1
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.1=py37h39e3cac_0
  - ipython=7.6.1=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.13.3=py37_0
  - jupyter_client=5.2.4=py37_0
  - jupyter_core=4.5.0=py_0
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - matplotlib=3.1.0=py37h54f8f79_0
  - mkl=2019.4=233
  - mkl_fft=1.0.12=py37h5e564d8_0
  - mkl_random=1.0.2=py37h27c97d8_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.16.4=py37hacdab7b_0
  - numpy-base=1.16.4=py37h6575580_0
  - openssl=1.1.1c=h1de35cc_1
  - pandas=0.24.2=py37h0a44026_0
  - parso=0.5.0=py_0
  - patsy=0.5.1=py37_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.1.1=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - ptyprocess=0.6.0=py37_0
  - pygments=2.4.2=py_0
  - pyparsing=2.4.0=py_0
  - python=3.7.3=h359304d_0
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.1=py_0
  - pyzmq=18.0.0=py37h0a44026_0
  - readline=7.0=h1de35cc_5
  - scipy=1.2.1=py37h1410ff5_0
  - seaborn=0.9.0=py37_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.28.0=ha441bb4_0
  - statsmodels=0.10.0=py37h1d22016_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py37h1de35cc_0
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.22.0
    - h5py==2.9.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - protobuf==3.9.0
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - termcolor==1.1.0
    - werkzeug==0.15.4
    - wrapt==1.11.2

