wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.35
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.0
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 50
