wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.22
    framework: tensorflow
    is_jupyter_run: true
    python_version: 3.7.4
batch_size:
  desc: null
  value: 10
epochs:
  desc: null
  value: 50
